# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 870)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 870))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 870))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 10, 1191, 851))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.PhotoBox_Tab1 = QtWidgets.QLabel(self.page)
        self.PhotoBox_Tab1.setGeometry(QtCore.QRect(10, -10, 641, 851))
        self.PhotoBox_Tab1.setTabletTracking(False)
        self.PhotoBox_Tab1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.PhotoBox_Tab1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PhotoBox_Tab1.setFrameShape(QtWidgets.QFrame.Box)
        self.PhotoBox_Tab1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PhotoBox_Tab1.setLineWidth(2)
        self.PhotoBox_Tab1.setMidLineWidth(0)
        self.PhotoBox_Tab1.setText("")
        self.PhotoBox_Tab1.setTextFormat(QtCore.Qt.AutoText)
        self.PhotoBox_Tab1.setAlignment(QtCore.Qt.AlignCenter)
        self.PhotoBox_Tab1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.PhotoBox_Tab1.setObjectName("PhotoBox_Tab1")
        self.Surname_Tab1 = QtWidgets.QLineEdit(self.page)
        self.Surname_Tab1.setGeometry(QtCore.QRect(820, 10, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Surname_Tab1.setFont(font)
        self.Surname_Tab1.setObjectName("Surname_Tab1")
        self.Midname_Label_Tab1 = QtWidgets.QLabel(self.page)
        self.Midname_Label_Tab1.setGeometry(QtCore.QRect(670, 90, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Midname_Label_Tab1.setFont(font)
        self.Midname_Label_Tab1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Midname_Label_Tab1.setObjectName("Midname_Label_Tab1")
        self.Name_Tab1 = QtWidgets.QLineEdit(self.page)
        self.Name_Tab1.setGeometry(QtCore.QRect(820, 50, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Name_Tab1.setFont(font)
        self.Name_Tab1.setObjectName("Name_Tab1")
        self.Name_Label_Tab1 = QtWidgets.QLabel(self.page)
        self.Name_Label_Tab1.setGeometry(QtCore.QRect(670, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Name_Label_Tab1.setFont(font)
        self.Name_Label_Tab1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Name_Label_Tab1.setObjectName("Name_Label_Tab1")
        self.Post_Tab1 = QtWidgets.QComboBox(self.page)
        self.Post_Tab1.setGeometry(QtCore.QRect(820, 210, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Post_Tab1.setFont(font)
        self.Post_Tab1.setObjectName("Post_Tab1")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Tab1.addItem("")
        self.Post_Label_Tab1 = QtWidgets.QLabel(self.page)
        self.Post_Label_Tab1.setGeometry(QtCore.QRect(670, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Post_Label_Tab1.setFont(font)
        self.Post_Label_Tab1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Post_Label_Tab1.setObjectName("Post_Label_Tab1")
        self.Midname_Tab1 = QtWidgets.QLineEdit(self.page)
        self.Midname_Tab1.setGeometry(QtCore.QRect(820, 90, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Midname_Tab1.setFont(font)
        self.Midname_Tab1.setObjectName("Midname_Tab1")
        self.Date_Lable_Tab1 = QtWidgets.QLabel(self.page)
        self.Date_Lable_Tab1.setGeometry(QtCore.QRect(670, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Date_Lable_Tab1.setFont(font)
        self.Date_Lable_Tab1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Date_Lable_Tab1.setObjectName("Date_Lable_Tab1")
        self.Institute_Label_Tab1 = QtWidgets.QLabel(self.page)
        self.Institute_Label_Tab1.setGeometry(QtCore.QRect(670, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Institute_Label_Tab1.setFont(font)
        self.Institute_Label_Tab1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Institute_Label_Tab1.setObjectName("Institute_Label_Tab1")
        self.Surname_Label_Tab1 = QtWidgets.QLabel(self.page)
        self.Surname_Label_Tab1.setGeometry(QtCore.QRect(670, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Surname_Label_Tab1.setFont(font)
        self.Surname_Label_Tab1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Surname_Label_Tab1.setObjectName("Surname_Label_Tab1")
        self.Institute_Tab1 = QtWidgets.QComboBox(self.page)
        self.Institute_Tab1.setGeometry(QtCore.QRect(820, 170, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Institute_Tab1.setFont(font)
        self.Institute_Tab1.setObjectName("Institute_Tab1")
        self.Institute_Tab1.addItem("")
        self.Institute_Tab1.addItem("")
        self.Institute_Tab1.addItem("")
        self.Institute_Tab1.addItem("")
        self.Institute_Tab1.addItem("")
        self.AddToDb_Tab1 = QtWidgets.QPushButton(self.page)
        self.AddToDb_Tab1.setEnabled(False)
        self.AddToDb_Tab1.setGeometry(QtCore.QRect(660, 790, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.AddToDb_Tab1.setFont(font)
        self.AddToDb_Tab1.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefix/icons/icon (5).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddToDb_Tab1.setIcon(icon)
        self.AddToDb_Tab1.setIconSize(QtCore.QSize(36, 36))
        self.AddToDb_Tab1.setObjectName("AddToDb_Tab1")
        self.DeletePhoto_Tab1 = QtWidgets.QPushButton(self.page)
        self.DeletePhoto_Tab1.setEnabled(False)
        self.DeletePhoto_Tab1.setGeometry(QtCore.QRect(660, 360, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.DeletePhoto_Tab1.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/prefix/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DeletePhoto_Tab1.setIcon(icon1)
        self.DeletePhoto_Tab1.setIconSize(QtCore.QSize(24, 24))
        self.DeletePhoto_Tab1.setObjectName("DeletePhoto_Tab1")
        self.UploadPhoto_Tab1 = QtWidgets.QPushButton(self.page)
        self.UploadPhoto_Tab1.setGeometry(QtCore.QRect(660, 260, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.UploadPhoto_Tab1.setFont(font)
        self.UploadPhoto_Tab1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.UploadPhoto_Tab1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.UploadPhoto_Tab1.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/prefix/icons/down-arrow-on-horizontal-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UploadPhoto_Tab1.setIcon(icon2)
        self.UploadPhoto_Tab1.setIconSize(QtCore.QSize(24, 24))
        self.UploadPhoto_Tab1.setObjectName("UploadPhoto_Tab1")
        self.Recognize_Tab1 = QtWidgets.QPushButton(self.page)
        self.Recognize_Tab1.setEnabled(False)
        self.Recognize_Tab1.setGeometry(QtCore.QRect(660, 310, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Recognize_Tab1.setFont(font)
        self.Recognize_Tab1.setStyleSheet("div {\n"
"    background: #007E3E; /* Цвет фона */\n"
"    color: #fff; /* Цвет текста */\n"
"    padding: 10px; /* Поля вокруг текста */\n"
"    border-radius: 5px; /* Уголки */\n"
"   }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/prefix/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Recognize_Tab1.setIcon(icon3)
        self.Recognize_Tab1.setIconSize(QtCore.QSize(24, 24))
        self.Recognize_Tab1.setObjectName("Recognize_Tab1")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(660, 0, 531, 251))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Date_Tab1 = QtWidgets.QDateEdit(self.page)
        self.Date_Tab1.setGeometry(QtCore.QRect(820, 130, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Date_Tab1.setFont(font)
        self.Date_Tab1.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Date_Tab1.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.Date_Tab1.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.Date_Tab1.setCalendarPopup(True)
        self.Date_Tab1.setTimeSpec(QtCore.Qt.LocalTime)
        self.Date_Tab1.setObjectName("Date_Tab1")
        self.label_2.raise_()
        self.PhotoBox_Tab1.raise_()
        self.Surname_Tab1.raise_()
        self.Midname_Label_Tab1.raise_()
        self.Name_Tab1.raise_()
        self.Name_Label_Tab1.raise_()
        self.Post_Tab1.raise_()
        self.Post_Label_Tab1.raise_()
        self.Midname_Tab1.raise_()
        self.Date_Lable_Tab1.raise_()
        self.Institute_Label_Tab1.raise_()
        self.Surname_Label_Tab1.raise_()
        self.Institute_Tab1.raise_()
        self.AddToDb_Tab1.raise_()
        self.DeletePhoto_Tab1.raise_()
        self.UploadPhoto_Tab1.raise_()
        self.Recognize_Tab1.raise_()
        self.Date_Tab1.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.DeleteFromDb_Tab2 = QtWidgets.QPushButton(self.page_2)
        self.DeleteFromDb_Tab2.setEnabled(False)
        self.DeleteFromDb_Tab2.setGeometry(QtCore.QRect(960, 0, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteFromDb_Tab2.setFont(font)
        self.DeleteFromDb_Tab2.setIcon(icon1)
        self.DeleteFromDb_Tab2.setIconSize(QtCore.QSize(22, 22))
        self.DeleteFromDb_Tab2.setObjectName("DeleteFromDb_Tab2")
        self.Search_Tab2 = QtWidgets.QLineEdit(self.page_2)
        self.Search_Tab2.setGeometry(QtCore.QRect(10, 0, 941, 31))
        self.Search_Tab2.setObjectName("Search_Tab2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(170, 660, 441, 191))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.Recognize_Tab2 = QtWidgets.QPushButton(self.page_2)
        self.Recognize_Tab2.setEnabled(False)
        self.Recognize_Tab2.setGeometry(QtCore.QRect(620, 810, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Recognize_Tab2.setFont(font)
        self.Recognize_Tab2.setStyleSheet("div {\n"
"    background: #007E3E; /* Цвет фона */\n"
"    color: #fff; /* Цвет текста */\n"
"    padding: 10px; /* Поля вокруг текста */\n"
"    border-radius: 5px; /* Уголки */\n"
"   }")
        self.Recognize_Tab2.setIcon(icon3)
        self.Recognize_Tab2.setIconSize(QtCore.QSize(22, 22))
        self.Recognize_Tab2.setObjectName("Recognize_Tab2")
        self.DeletePhoto_Tab2 = QtWidgets.QPushButton(self.page_2)
        self.DeletePhoto_Tab2.setEnabled(False)
        self.DeletePhoto_Tab2.setGeometry(QtCore.QRect(620, 710, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.DeletePhoto_Tab2.setFont(font)
        self.DeletePhoto_Tab2.setIcon(icon1)
        self.DeletePhoto_Tab2.setIconSize(QtCore.QSize(22, 22))
        self.DeletePhoto_Tab2.setObjectName("DeletePhoto_Tab2")
        self.Surname_Tab2 = QtWidgets.QLineEdit(self.page_2)
        self.Surname_Tab2.setGeometry(QtCore.QRect(300, 670, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Surname_Tab2.setFont(font)
        self.Surname_Tab2.setObjectName("Surname_Tab2")
        self.PhotoBox_Tab2 = QtWidgets.QLabel(self.page_2)
        self.PhotoBox_Tab2.setGeometry(QtCore.QRect(10, 660, 151, 191))
        self.PhotoBox_Tab2.setFrameShape(QtWidgets.QFrame.Panel)
        self.PhotoBox_Tab2.setLineWidth(2)
        self.PhotoBox_Tab2.setText("")
        self.PhotoBox_Tab2.setObjectName("PhotoBox_Tab2")
        self.SaveChanges_Tab2 = QtWidgets.QPushButton(self.page_2)
        self.SaveChanges_Tab2.setEnabled(False)
        self.SaveChanges_Tab2.setGeometry(QtCore.QRect(620, 660, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.SaveChanges_Tab2.setFont(font)
        self.SaveChanges_Tab2.setStyleSheet("div {\n"
"    background: #007E3E; /* Цвет фона */\n"
"    color: #fff; /* Цвет текста */\n"
"    padding: 10px; /* Поля вокруг текста */\n"
"    border-radius: 5px; /* Уголки */\n"
"   }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/prefix/icons/Artboard_73-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveChanges_Tab2.setIcon(icon4)
        self.SaveChanges_Tab2.setIconSize(QtCore.QSize(30, 30))
        self.SaveChanges_Tab2.setObjectName("SaveChanges_Tab2")
        self.UploadPhoto_Tab2 = QtWidgets.QPushButton(self.page_2)
        self.UploadPhoto_Tab2.setEnabled(False)
        self.UploadPhoto_Tab2.setGeometry(QtCore.QRect(620, 760, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.UploadPhoto_Tab2.setFont(font)
        self.UploadPhoto_Tab2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.UploadPhoto_Tab2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.UploadPhoto_Tab2.setStyleSheet("")
        self.UploadPhoto_Tab2.setIcon(icon2)
        self.UploadPhoto_Tab2.setIconSize(QtCore.QSize(20, 20))
        self.UploadPhoto_Tab2.setObjectName("UploadPhoto_Tab2")
        self.Post_Label_Tab2 = QtWidgets.QLabel(self.page_2)
        self.Post_Label_Tab2.setGeometry(QtCore.QRect(180, 820, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Post_Label_Tab2.setFont(font)
        self.Post_Label_Tab2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Post_Label_Tab2.setObjectName("Post_Label_Tab2")
        self.Midname_Label_Tab2 = QtWidgets.QLabel(self.page_2)
        self.Midname_Label_Tab2.setGeometry(QtCore.QRect(180, 730, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Midname_Label_Tab2.setFont(font)
        self.Midname_Label_Tab2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Midname_Label_Tab2.setObjectName("Midname_Label_Tab2")
        self.Name_Label_Tab2 = QtWidgets.QLabel(self.page_2)
        self.Name_Label_Tab2.setGeometry(QtCore.QRect(180, 700, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Name_Label_Tab2.setFont(font)
        self.Name_Label_Tab2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Name_Label_Tab2.setObjectName("Name_Label_Tab2")
        self.Post_Tab2 = QtWidgets.QComboBox(self.page_2)
        self.Post_Tab2.setGeometry(QtCore.QRect(300, 820, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Post_Tab2.setFont(font)
        self.Post_Tab2.setObjectName("Post_Tab2")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Post_Tab2.addItem("")
        self.Institute_Tab2 = QtWidgets.QComboBox(self.page_2)
        self.Institute_Tab2.setGeometry(QtCore.QRect(300, 790, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Institute_Tab2.setFont(font)
        self.Institute_Tab2.setObjectName("Institute_Tab2")
        self.Institute_Tab2.addItem("")
        self.Institute_Tab2.addItem("")
        self.Institute_Tab2.addItem("")
        self.Institute_Tab2.addItem("")
        self.Institute_Tab2.addItem("")
        self.Name_Tab2 = QtWidgets.QLineEdit(self.page_2)
        self.Name_Tab2.setGeometry(QtCore.QRect(300, 700, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Name_Tab2.setFont(font)
        self.Name_Tab2.setText("")
        self.Name_Tab2.setObjectName("Name_Tab2")
        self.Institute_Label_Tab2 = QtWidgets.QLabel(self.page_2)
        self.Institute_Label_Tab2.setGeometry(QtCore.QRect(180, 790, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Institute_Label_Tab2.setFont(font)
        self.Institute_Label_Tab2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Institute_Label_Tab2.setObjectName("Institute_Label_Tab2")
        self.Midname_Tab2 = QtWidgets.QLineEdit(self.page_2)
        self.Midname_Tab2.setGeometry(QtCore.QRect(300, 730, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Midname_Tab2.setFont(font)
        self.Midname_Tab2.setObjectName("Midname_Tab2")
        self.Date_Label_Tab2 = QtWidgets.QLabel(self.page_2)
        self.Date_Label_Tab2.setGeometry(QtCore.QRect(180, 760, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Date_Label_Tab2.setFont(font)
        self.Date_Label_Tab2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Date_Label_Tab2.setObjectName("Date_Label_Tab2")
        self.Surname_Label_Tab2 = QtWidgets.QLabel(self.page_2)
        self.Surname_Label_Tab2.setGeometry(QtCore.QRect(180, 670, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Surname_Label_Tab2.setFont(font)
        self.Surname_Label_Tab2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Surname_Label_Tab2.setObjectName("Surname_Label_Tab2")
        self.Table_Tab2 = QtWidgets.QTableWidget(self.page_2)
        self.Table_Tab2.setGeometry(QtCore.QRect(10, 40, 1181, 611))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Table_Tab2.sizePolicy().hasHeightForWidth())
        self.Table_Tab2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Table_Tab2.setFont(font)
        self.Table_Tab2.setLineWidth(1)
        self.Table_Tab2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Table_Tab2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Table_Tab2.setAlternatingRowColors(False)
        self.Table_Tab2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.Table_Tab2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.Table_Tab2.setShowGrid(True)
        self.Table_Tab2.setGridStyle(QtCore.Qt.SolidLine)
        self.Table_Tab2.setRowCount(0)
        self.Table_Tab2.setColumnCount(7)
        self.Table_Tab2.setObjectName("Table_Tab2")
        item = QtWidgets.QTableWidgetItem()
        self.Table_Tab2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.Table_Tab2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_Tab2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table_Tab2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Table_Tab2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.Table_Tab2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.Table_Tab2.setHorizontalHeaderItem(6, item)
        self.Table_Tab2.horizontalHeader().setCascadingSectionResizes(False)
        self.Table_Tab2.horizontalHeader().setDefaultSectionSize(150)
        self.Table_Tab2.horizontalHeader().setHighlightSections(False)
        self.Table_Tab2.horizontalHeader().setMinimumSectionSize(100)
        self.Table_Tab2.horizontalHeader().setSortIndicatorShown(True)
        self.Table_Tab2.horizontalHeader().setStretchLastSection(True)
        self.Date_Tab2 = QtWidgets.QDateEdit(self.page_2)
        self.Date_Tab2.setGeometry(QtCore.QRect(300, 760, 301, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Date_Tab2.setFont(font)
        self.Date_Tab2.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Date_Tab2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.Date_Tab2.setCalendarPopup(True)
        self.Date_Tab2.setObjectName("Date_Tab2")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 70, 81, 71))
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/prefix/icons/icon (6).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 81, 71))
        self.pushButton_4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/prefix/icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setChecked(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.OpenWebcam_Tab1 = QtWidgets.QPushButton(self.centralwidget)
        self.OpenWebcam_Tab1.setGeometry(QtCore.QRect(0, 580, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OpenWebcam_Tab1.setFont(font)
        self.OpenWebcam_Tab1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/prefix/icons/dslr-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenWebcam_Tab1.setIcon(icon7)
        self.OpenWebcam_Tab1.setIconSize(QtCore.QSize(50, 50))
        self.OpenWebcam_Tab1.setFlat(True)
        self.OpenWebcam_Tab1.setObjectName("OpenWebcam_Tab1")
        self.About = QtWidgets.QPushButton(self.centralwidget)
        self.About.setGeometry(QtCore.QRect(0, 780, 81, 71))
        self.About.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/prefix/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.About.setIcon(icon8)
        self.About.setIconSize(QtCore.QSize(50, 50))
        self.About.setFlat(True)
        self.About.setObjectName("About")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1281, 871))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setLineWidth(3)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 81, 871))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(3)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.StartRecognize = QtWidgets.QPushButton(self.centralwidget)
        self.StartRecognize.setGeometry(QtCore.QRect(0, 510, 81, 71))
        self.StartRecognize.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/prefix/icons/play.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartRecognize.setIcon(icon9)
        self.StartRecognize.setIconSize(QtCore.QSize(50, 50))
        self.StartRecognize.setFlat(True)
        self.StartRecognize.setObjectName("StartRecognize")
        self.label_6.raise_()
        self.label_5.raise_()
        self.stackedWidget.raise_()
        self.pushButton_5.raise_()
        self.pushButton_4.raise_()
        self.OpenWebcam_Tab1.raise_()
        self.About.raise_()
        self.StartRecognize.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionZoom_In_25 = QtWidgets.QAction(MainWindow)
        self.actionZoom_In_25.setObjectName("actionZoom_In_25")
        self.actionZoom_Out_25 = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out_25.setObjectName("actionZoom_Out_25")
        self.actionNormal_Size = QtWidgets.QAction(MainWindow)
        self.actionNormal_Size.setObjectName("actionNormal_Size")
        self.actionFit_to_Window = QtWidgets.QAction(MainWindow)
        self.actionFit_to_Window.setObjectName("actionFit_to_Window")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Распознавание лиц ©"))
        self.Surname_Tab1.setInputMask(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
        self.Midname_Label_Tab1.setText(_translate("MainWindow", "Отчество"))
        self.Name_Tab1.setInputMask(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
        self.Name_Label_Tab1.setText(_translate("MainWindow", "Имя"))
        self.Post_Tab1.setItemText(0, _translate("MainWindow", "Студент"))
        self.Post_Tab1.setItemText(1, _translate("MainWindow", "Аспирант"))
        self.Post_Tab1.setItemText(2, _translate("MainWindow", "Бухгалтер"))
        self.Post_Tab1.setItemText(3, _translate("MainWindow", "Ректор"))
        self.Post_Tab1.setItemText(4, _translate("MainWindow", "Заведующий кафедры"))
        self.Post_Tab1.setItemText(5, _translate("MainWindow", "Преподаватель"))
        self.Post_Tab1.setItemText(6, _translate("MainWindow", "Проректор"))
        self.Post_Tab1.setItemText(7, _translate("MainWindow", "Доцент"))
        self.Post_Tab1.setItemText(8, _translate("MainWindow", "Ст. преподаватель"))
        self.Post_Tab1.setItemText(9, _translate("MainWindow", "Уборщик"))
        self.Post_Tab1.setItemText(10, _translate("MainWindow", "Техник"))
        self.Post_Tab1.setItemText(11, _translate("MainWindow", "Инженер"))
        self.Post_Label_Tab1.setText(_translate("MainWindow", "Должность"))
        self.Midname_Tab1.setInputMask(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
        self.Date_Lable_Tab1.setText(_translate("MainWindow", "Дата рождения"))
        self.Institute_Label_Tab1.setText(_translate("MainWindow", "Институт"))
        self.Surname_Label_Tab1.setText(_translate("MainWindow", "Фамилия"))
        self.Institute_Tab1.setItemText(0, _translate("MainWindow", "ИЛИП"))
        self.Institute_Tab1.setItemText(1, _translate("MainWindow", "ИЛАС"))
        self.Institute_Tab1.setItemText(2, _translate("MainWindow", "ИТМИТЛ"))
        self.Institute_Tab1.setItemText(3, _translate("MainWindow", "ИХПБ"))
        self.Institute_Tab1.setItemText(4, _translate("MainWindow", "ИУИЭЛС"))
        self.AddToDb_Tab1.setText(_translate("MainWindow", " Загрузить карточку в базу"))
        self.DeletePhoto_Tab1.setText(_translate("MainWindow", "Удалить изображение"))
        self.UploadPhoto_Tab1.setText(_translate("MainWindow", " Загрузить изображение"))
        self.Recognize_Tab1.setText(_translate("MainWindow", " Распознать лицо"))
        self.DeleteFromDb_Tab2.setText(_translate("MainWindow", "Удалить из БД"))
        self.Recognize_Tab2.setText(_translate("MainWindow", " Распознать лицо"))
        self.DeletePhoto_Tab2.setText(_translate("MainWindow", "Удалить изображение"))
        self.Surname_Tab2.setInputMask(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
        self.SaveChanges_Tab2.setText(_translate("MainWindow", "Сохранить изменения"))
        self.UploadPhoto_Tab2.setText(_translate("MainWindow", " Загрузить новое изображение"))
        self.Post_Label_Tab2.setText(_translate("MainWindow", "Должность"))
        self.Midname_Label_Tab2.setText(_translate("MainWindow", "Отчество"))
        self.Name_Label_Tab2.setText(_translate("MainWindow", "Имя"))
        self.Post_Tab2.setItemText(0, _translate("MainWindow", "Студент"))
        self.Post_Tab2.setItemText(1, _translate("MainWindow", "Аспирант"))
        self.Post_Tab2.setItemText(2, _translate("MainWindow", "Бухгалтер"))
        self.Post_Tab2.setItemText(3, _translate("MainWindow", "Ректор"))
        self.Post_Tab2.setItemText(4, _translate("MainWindow", "Заведующий кафедры"))
        self.Post_Tab2.setItemText(5, _translate("MainWindow", "Преподаватель"))
        self.Post_Tab2.setItemText(6, _translate("MainWindow", "Проректор"))
        self.Post_Tab2.setItemText(7, _translate("MainWindow", "Доцент"))
        self.Post_Tab2.setItemText(8, _translate("MainWindow", "Ст. преподаватель"))
        self.Post_Tab2.setItemText(9, _translate("MainWindow", "Уборщик"))
        self.Post_Tab2.setItemText(10, _translate("MainWindow", "Техник"))
        self.Post_Tab2.setItemText(11, _translate("MainWindow", "Инженер"))
        self.Institute_Tab2.setItemText(0, _translate("MainWindow", "ИЛИП"))
        self.Institute_Tab2.setItemText(1, _translate("MainWindow", "ИЛАС"))
        self.Institute_Tab2.setItemText(2, _translate("MainWindow", "ИТМИТЛ"))
        self.Institute_Tab2.setItemText(3, _translate("MainWindow", "ИХПБ"))
        self.Institute_Tab2.setItemText(4, _translate("MainWindow", "ИУИЭЛС"))
        self.Name_Tab2.setInputMask(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
        self.Institute_Label_Tab2.setText(_translate("MainWindow", "Институт"))
        self.Midname_Tab2.setInputMask(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"))
        self.Date_Label_Tab2.setText(_translate("MainWindow", "Дата рождения"))
        self.Surname_Label_Tab2.setText(_translate("MainWindow", "Фамилия"))
        self.Table_Tab2.setSortingEnabled(True)
        item = self.Table_Tab2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.Table_Tab2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Фамилия"))
        item = self.Table_Tab2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.Table_Tab2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Отчество"))
        item = self.Table_Tab2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата рождения"))
        item = self.Table_Tab2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Институт"))
        item = self.Table_Tab2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Должность"))
        self.actionZoom_In_25.setText(_translate("MainWindow", "Zoom In (25%)"))
        self.actionZoom_Out_25.setText(_translate("MainWindow", "Zoom Out (25%)"))
        self.actionNormal_Size.setText(_translate("MainWindow", "Normal Size"))
        self.actionFit_to_Window.setText(_translate("MainWindow", "Fit to Window"))
import newresourse_rc_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
